### ISSUE TITLE
I am very interested in your result in the pdf, is there any updating?

### ISSUE THREAD

**Issue by xichaoqiang** [SigProSeismology/AMBITION-Noise#1]
I am very interested in your result in the pdf, is there any updating?

**Comment by SigProSeismology** [comment]
Thank you for your interest.
The idea of this study was to extract body waves from cross-correlation seismograms generated from ambient noise.
The proposal for the project was not granted, and research was halted.

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
That’s a pity.
